### ISSUE TITLE
NPT.owl inconsistent

### ISSUE THREAD

**Issue by jonathanbona** [addiehl/neuropsychological-testing-ontology#3]
In Protege 5.2, Hermit 1.3.8, the reasoner finds NPT.owl to be inconsistent:

<img width="1150" alt="Screen Shot 2019-04-05 at 11 37 02 AM" src="https://user-images.githubusercontent.com/78007/55642815-2ab9ab00-5797-11e9-900d-8b6edda9ee96.png">

**Comment by jonathanbona** [comment]
Temporary fix: move 'is measurement of' and 'is specification of' out from under 'is about'

Here's a version that reasons: https://github.com/jonathanbona/neuropsychological-testing-ontology/commit/29151d0f8107b9472b07836297c6bdf3cc882722

**Comment by addiehl** [comment]
Thanks Jonathan!

**Comment by APCox** [comment]
Axioms that were causing the inconsistency were removed in version 1.7.3. No errors were found by either ELK 0.4.3 or Hermit 1.4.3.456
